# Whether the plugin is enabled or not
plugin-enabled: true

# Whether newly spawned armor stands should have arms by default
arms: true

baseplate: # (smooth stone slabs)
  # Whether baseplates can be put on armor stands and taken off
  changeable: true

  # Whether an armor stand crafting recipe should be added that does not require the baseplate
  baseplate-less-recipe: true

pose-changing:
  # Whether players will be able to change poses of armor stands
  enabled: true

  # The list of armor stand poses that will be cycled through
  # The syntax for the poses is:
  # [ [ body pose ], [ head pose ], [ left arm pose ], [ left leg pose ], [ right arm pose ], [ right leg pose ] ]
  poses: [
    [ [ 0.0,0.0,0.0 ],[ 0.0,0.0,0.0 ],[ -10.0,0.0,-10.0 ],[ -1.0,0.0,-1.0 ],[ -15.0,0.0,10.0 ],[ 1.0,0.0,1.0 ] ],
    [ [ 0.0,0.0,0.0 ],[ 0.0,0.0,0.0 ],[ 0.0,0.0,0.0 ],[ 0.0,0.0,0.0 ],[ 0.0,0.0,0.0 ],[ 0.0,0.0,0.0 ] ],
    [ [ 0.0,0.0,2.0 ],[ 15.0,0.0,0.0 ],[ -30.0,15.0,15.0 ],[ -1.0,0.0,-1.0 ],[ -60.0,-20.0,-10.0 ],[ 1.0,0.0,1.0 ] ],
    [ [ 0.0,0.0,2.0 ],[ -5.0,0.0,0.0 ],[ 10.0,0.0,-5.0 ],[ -3.0,-3.0,-3.0 ],[ -60.0,20.0,-10.0 ],[ 3.0,3.0,3.0 ] ],
    [ [ 0.0,0.0,-2.0 ],[ -15.0,0.0,0.0 ],[ 20.0,0.0,-10.0 ],[ 5.0,-3.0,-3.0 ],[ -110.0,50.0,0.0 ],[ -5.0,3.0,3.0 ] ],
    [ [ 0.0,0.0,0.0 ],[ -15.0,0.0,0.0 ],[ -110.0,35.0,0.0 ],[ 5.0,-3.0,-3.0 ],[ -110.0,-35.0,0.0 ],[ -5.0,3.0,3.0 ] ],
    [ [ 0.0,0.0,0.0 ],[ -15.0,0.0,0.0 ],[ -110.0,-35.0,0.0 ],[ 5.0,-3.0,-3.0 ],[ -110.0,35.0,0.0 ],[ -5.0,3.0,3.0 ] ],
    [ [ 0.0,0.0,0.0 ],[ 0.0,0.0,0.0 ],[ 10.0,0.0,-5.0 ],[ -1.0,0.0,-1.0 ],[ -70.0,-40.0,0.0 ],[ 1.0,0.0,1.0 ] ],
    [ [ 0.0,0.0,0.0 ],[ 16.0,20.0,0.0 ],[ 4.0,8.0,237.0 ],[ -14.0,-18.0,-16.0 ],[ 246.0,0.0,89.0 ],[ 8.0,20.0,4.0 ] ],
    [ [ 0.0,0.0,0.0 ],[ -10.0,0.0,-5.0 ],[ -105.0,0.0,0.0 ],[ 7.0,0.0,0.0 ],[ -100.0,0.0,0.0 ],[ -46.0,0.0,0.0 ] ],
    [ [ 0.0,22.0,0.0 ],[ -5.0,18.0,0.0 ],[ 8.0,0.0,-114.0 ],[ -111.0,55.0,0.0 ],[ 0.0,84.0,111.0 ],[ 0.0,23.0,-13.0 ] ],
    [ [ 0.0,-18.0,0.0 ],[ -10.0,-20.0,0.0 ],[ 0.0,0.0,-112.0 ],[ 0.0,0.0,13.0 ],[ 8.0,90.0,111.0 ],[ -119.0,-42.0,0.0 ] ],
    [ [ 0.0,8.0,0.0 ],[ -4.0,67.0,0.0 ],[ 16.0,32.0,-8.0 ],[ 0.0,-75.0,-8.0 ],[ -99.0,63.0,0.0 ],[ 4.0,63.0,8.0 ] ]
  ]